name: "Terraform-Apply-Infra-Release"

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
      #checkov:skip=CKV_GHA_7: "The build output cannot be affected by user parameters other than the build entry point and the top-level source location. GitHub Actions workflow_dispatch 
      inputs:
          env_workspace:
            description: 'Terraform Workspace'
            required: true
            default: 'dev'
            type: choice
            options:
              - dev
              - staging
              - prod

permissions: read-all

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: "Set Workspace ${{ github.event.inputs.env_workspace }}"
        id: setworkspace
        run: |
         sed -i 's/env-dev/iac-${{ github.event.inputs.env_workspace }}/g' ./main.tf

      - name: "Terraform Init"
        id: init
        run: |
           terraform init --var-file ./${{ github.event.inputs.env_workspace }}-varfile.tfvars

      - name: Terraform Plan
        id: plan
        # if: github.event_name == 'push'
        run: terraform plan --var-file ./${{ github.event.inputs.env_workspace }}-varfile.tfvars -no-color
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve --var-file ./${{ github.event.inputs.env_workspace }}-varfile.tfvars
