name: "Terraform-Plan-Infra-Plan"

on:
  push:
    branches:
      - FeatureSA01
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Terraform Workspace'
        required: true
        default: 'iac-dev'
        type: choice
        options:
          - 'iac-dev'
          - 'iac-staging'
          - 'iac-prod'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="organization=github-tfc-ado"

      - name: Set Terraform Workspace
        id: workspace
        run: terraform workspace select ${{ github.event.inputs.workspace }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: terraform plan -no-color
