name: "Terraform-Plan-Infra-Plan"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      workspace:
        description: 'Select Terraform Cloud Workspace'
        required: true
        type: choice
        options:
          - iac-dev
          - iac-staging
          - iac-production

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="organization=${{ env.TF_VAR_org }}" -backend-config="workspaces.name=${{ github.event.inputs.workspace }}"

      - name: Select Terraform Cloud workspace
        run: terraform workspace select ${{ github.event.inputs.workspace }}
        continue-on-error: true  # Allow to continue if workspace doesn't exist

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
